Новые цели станции
ss14-ganimed/ENT14-Master pull request #134
Opened 2024-04-02 10:03 UTC by Gorox221

## Описание PR
Изменяет и добавляет новые цели станции.
Изменены:
-Цель на шаттл
-Цель на зоопарк
Добавлены:
-Цель на харвестер
-Улучшение реклемера и добычи руда
-Реставрация тех. помещений
-Цель на содержание фауны
-Цель на шахтерский оутпост

## Цель / Баланс
Разнообразие

## Медиа
![изображение](https://github.com/ss14-ganimed/ENT14-Master/assets/139872389/2e58900c-6de6-4321-a763-b63fc2721159)

- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует. 

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.

:cl: Gorox
- tweak: Добавлены новые цели, а так-же изменены некоторые старые.

2024-04-02 10:17 UTC, Yuoko commented
Сделай по нашей форме

2024-04-02 10:17 UTC, Yuoko commented
И выравняй

2024-04-02 19:19 UTC, Gorox221 commented
> Сделай по нашей форме

Сделал. Сделать "ЦЕЛЬ СТАНЦИИ" толстым нельзя, ломает все.

2024-04-04 10:00 UTC, Yuoko requested changes
Сравни с шаблоном в бумажной работе.

2024-04-05 09:18 UTC, Yuoko approved these changes
Вот теперь вроде нормально

2024-04-05 09:20 UTC, Yuoko requested changes
А, нет. Добавь цель на постройку метеоритной защиты нескольких сегментов станции на свой выбор. Мостик там и тд. С обязательным условием, в виде отступа от обшивки в 7 тайлов МИНИМУМ. Общее количество щитов должно быть не менее 30 штук.

2024-04-05 12:48 UTC, Yuoko commented on Resources/Locale/ru-RU/corvax/station-goal/station-goal-component.ftl
> +    Повышение уровня добычи до 11 и выше является нарушением техники безопасности и преступной халатностью.
```suggestion
    Повышение уровня добычи до 11 и выше является нарушением техники безопасности и преступной халатностью.
    ```
Я думаю это лишнее. Пусть сами как им удобно добывают, если не бояться мобов, пусть хоть на 20.

2024-04-06 13:20 UTC, merged